server:
  port: 8003
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_review
    username: root
    password: System@15

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HOTEL-RATING
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
