server:
  port: 8003
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_review
    username: root
    password: System@15

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver
